export const USERS = {
  gabe:    { name: 'Gabe',       username: '@gabe',           img: null,                     color: '#d4683c' },
  meech:   { name: 'Meech',      username: '@thebulltard',    img: '/avatars/meech.jpg',     color: '#60a5fa' },
  grove:   { name: 'Grove St',   username: '@grovest_nft',    img: '/avatars/grovest.jpg',   color: '#d4683c' },
  brazy:   { name: 'Lord Brazy', username: '@brazylord',      img: '/avatars/lordbrazy.jpg', color: '#a78bfa' },
  kelvin:  { name: 'Kelvin',     username: '@llegoelkelo',    img: '/avatars/kelvin.jpg',    color: '#34d399' },
  bagcalls:{ name: 'BagCalls',   username: '@bagcalls',       img: '/avatars/bagcalls.jpg',  color: '#f87171' },
  ryan:    { name: 'Ryan',       username: '@ryankane',       img: '/avatars/ryan.jpg',      color: '#2dd4bf' },
  edgar:   { name: 'edgar',      username: '@edgarpavlovsky', img: '/avatars/edgar.jpg',     color: '#a3e635' },
}

export const PROFILES = {
  gabe: {
    ...USERS.gabe,
    displayName: 'Gabe',
    handle: '@gabe',
    bio: 'Building SLUGS · Solana degen · letting agents do the work',
    following: 12,
    followers: 847,
    joined: 'May 2025',
    agents: [
      {
        slug: 'scout',
        fullSlug: '@gabe/scout',
        description: 'Momentum-based SOL/USDC swing trader. Enters on breakouts, exits on RSI divergence.',
        strategy: 'Momentum',
        chain: 'Solana',
        status: 'active',
        pnl: '+$2,841.20',
        pnlPct: '+18.4%',
        positive: true,
        winRate: '67%',
        trades: 43,
        avgHold: '4.2h',
        color: '#d4683c',
        recentTrades: [
          { token: 'SOL',  action: 'buy',  amount: '12 SOL',    pnl: '+$284.10', positive: true,  time: '2h ago' },
          { token: 'BONK', action: 'sell', amount: '4.2M BONK', pnl: '+$81.20',  positive: true,  time: '6h ago' },
          { token: 'WIF',  action: 'sell', amount: '620 WIF',   pnl: '-$34.00',  positive: false, time: '1d ago' },
          { token: 'JUP',  action: 'buy',  amount: '800 JUP',   pnl: '+$57.40',  positive: true,  time: '1d ago' },
          { token: 'RAY',  action: 'sell', amount: '340 RAY',   pnl: '+$112.80', positive: true,  time: '2d ago' },
        ],
      },
      {
        slug: 'dca',
        fullSlug: '@gabe/dca',
        description: 'Weekly DCA into SOL and ETH. No noise, just accumulation.',
        strategy: 'DCA',
        chain: 'Multi-chain',
        status: 'active',
        pnl: '+$1,204.50',
        pnlPct: '+9.1%',
        positive: true,
        winRate: '82%',
        trades: 28,
        avgHold: '7d',
        color: '#2dd4bf',
        recentTrades: [
          { token: 'SOL', action: 'buy', amount: '5 SOL',   pnl: '+$148.20', positive: true, time: '3d ago' },
          { token: 'ETH', action: 'buy', amount: '0.1 ETH', pnl: '+$62.00',  positive: true, time: '10d ago' },
          { token: 'SOL', action: 'buy', amount: '5 SOL',   pnl: '+$94.50',  positive: true, time: '17d ago' },
        ],
      },
    ],
  },
}
